### ISSUE TITLE
Adding more queries to an existing project/scenario

### ISSUE THREAD

**Issue by cahartin** [JGCRI/rgcam#39]
If the scenario exists in the project file but we want to add more queries, will `rgcam` stop because it sees the scenario already there or is it looking to see that those queries are not there?

FYI: i haven't actually tested which is the case.

**Comment by pralitp** [comment]
Short answer is no it will not stop.  For more details keep reading:

It doesn't mind about existing scenarios by themselves but does give consideration when a scenario + query combination already exists.  This behavior is controlled by the `clobber` parameter.  By default it is set to `FALSE` so that the results that already exist in your project will not get overwritten.  You can set it to `TRUE` to force it to update that data.

Note it is set to `FALSE` by default for a number of reasons but for me the most useful reason is that if you have a batch query file that you have already run but then realize you need to add more queries.  You can just add the new queries to your existing batch file and re-run the whole thing.  Except the queries that had already been run will just skip because `clobber=FALSE` thus saving you time for not having to re-run for results you already have and just adding for the new ones.

**Comment by cahartin** [comment]
@pralitp thanks!  I'm going to try that now.
