### ISSUE TITLE
how to get the  aggregated land allocation with different AEZ

### ISSUE THREAD

**Issue by SmileEric** [JGCRI/rgcam#53]
In the GCAM Model Interface, the queries include "Aggregated Land Allocation" . But using rgcam package, I couldn't find the "aggregated land allocation".  How to read "Aggregated Land Allocation" using rgcam package.

**Comment by pralitp** [comment]
The queries and database included with the `rgcam` package are intended to be for example only.

You should always use the queries associated with the GCAM workspace you are using.  There are many different ways you can use those queries in the `rgcam` package.
You could create your own batch queries file by copying them out of the query file in `output/queries/Main_queries.xml`, using `CTRL-C / CTRL-V` from an interactive Model Interface session, using the batch file in `output/gcam_diagnostics/batch_queries/Model_verification_queries.xml` as a template.  Or running a single query at a time using any of the methods described in the vignette examples (and of course instead of referencing the queries in the `SAMPLE.QUERIES` you should reference them out of your GCAM workspace) :
https://github.com/JGCRI/rgcam/blob/master/vignettes/rgcam-usecases.Rmd
